doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_sqlsrv'
                charset: UTF-8
            old:
                url: '%env(DATABASE_OLD_URL)%'
                driver: 'pdo_sqlsrv'
                charset: UTF-8
    
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            old:
                connection: old
                auto_mapping: false
                mappings:
                    Old:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/EntityOld'
                        prefix: 'App\EntityOld'
                        alias: Old