version: '3'
services:
  dbciap:
    image: microsoft/mssql-server-linux
    container_name: dbciap
    restart: always
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "WdUCJWOUYi484fZRyCUR"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"
    volumes:
      - .:/home
  dbmi:
    image: microsoft/mssql-server-linux
    container_name: dbmutua
    restart: always
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "WdUCJWOUYi484fZRyCUR"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1434:1433"