version: '3'
services:
  dbciap:
    image: microsoft/mssql-server-linux
    restart: always
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "WdUCJWOUYi484fZRyCUR"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  dbmi:
    image: microsoft/mssql-server-linux
    restart: always
    expose:
      - "1433"
    environment:
      SA_PASSWORD: "WdUCJWOUYi484fZRyCUR"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"