CREATE DATABASE db_ciap;

use db_ciap;

CREATE TABLE [dbo].[CIA_Associado](
	[Ass_ID] [int] IDENTITY(1,1) NOT NULL,
	[Ass_Age_ID] [tinyint] NULL,
	[Ass_Sit_ID] [tinyint] NULL,
	[Ass_Ban_Codigo] [char](3) NULL,
	[Ass_CPF] [char](11) NULL,
	[Ass_Nome] [varchar](50) NULL,
	[Ass_Data_Inscricao] [smalldatetime] NULL,
	[Ass_Endereco_Res] [varchar](40) NULL,
	[Ass_Bairro_Res] [varchar](20) NULL,
	[Ass_Cidade_Res] [varchar](20) NULL,
	[Ass_Cep_Res] [char](8) NULL,
	[Ass_UF_Res] [char](2) NULL,
	[Ass_Endereco_Com] [varchar](40) NULL,
	[Ass_Bairro_Com] [varchar](20) NULL,
	[Ass_Cidade_Com] [varchar](20) NULL,
	[Ass_UF_Com] [char](2) NULL,
	[Ass_Cep_Com] [char](8) NULL,
	[Ass_Telefone1_Res] [char](11) NULL,
	[Ass_Telefone2_Res] [char](11) NULL,
	[Ass_Celular_Res] [char](11) NULL,
	[Ass_Telefone1_Com] [char](11) NULL,
	[Ass_Telefone2_Com] [char](11) NULL,
	[Ass_Fax_Com] [char](10) NULL,
	[Ass_Email_Res] [varchar](70) NULL,
	[Ass_Email_Com] [varchar](70) NULL,
	[Ass_Data_Nascimento] [smalldatetime] NULL,
	[Ass_Naturalidade] [varchar](25) NULL,
	[Ass_Nacionalidade] [varchar](20) NULL,
	[Ass_RG] [varchar](15) NULL,
	[Ass_RG_Org_Emissor] [varchar](15) NULL,
	[Ass_Sexo] [char](1) NULL,
	[Ass_Data_Homologacao] [smalldatetime] NULL,
	[Ass_Agencia] [char](10) NULL,
	[Ass_Conta] [varchar](15) NULL,
	[Ass_CPF_Conjuge] [varchar](11) NULL,
	[Ass_RG_Conjuge] [varchar](15) NULL,
	[Ass_RG_Org_Emissor_Conjuge] [varchar](15) NULL,
	CONSTRAINT [PK_CIA_ASSOCIADO] PRIMARY KEY CLUSTERED
	( [Ass_ID] ASC )
)
